### ISSUE TITLE
eventsNow does not display all current events

### ISSUE THREAD

**Issue by ebartz** [ajrosen/icalPal#28]
Hi there,

using version 3.2.0.

For some reason I don't see the currently happening event.

It works with icalBuddy but does not with icalPal. When I just use events, it displays the event I would be searching for.

Any hint, how I can further debug?

**Comment by ajrosen** [comment]
It's not your imagination, there was a bug.  Fixed in 3.3.0.

Thanks!

**Comment by ebartz** [comment]
@ajrosen 

Well I am not so sure about that.

Installed 3.3.0 and am still having issues where I dont get the same number of meetings.

For instance there is a meeting that I for some reason don't see.

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/324933a3-2cb3-4935-be0d-270f54dbca9a" />

Do you have any Idea how I could debug this?

**Comment by ajrosen** [comment]
Grr.  I can reproduce it though.  For me it's leaving out repeated events.

**Comment by ajrosen** [comment]
Ok, I think I've got it fixed, for real.

There is version [3.4.0.pre](https://github.com/ajrosen/icalPal/releases/tag/icalpal-3.4.0.pre) if you'd like to try it before I release it.

**Comment by ebartz** [comment]
Thanks for looking into this.

But with the same options I still get different results:

<img width="426" alt="Image" src="https://github.com/user-attachments/assets/c3a64bfe-b8b6-4c47-aa02-0296cf35f4ee" />

If I look more into the details:

<img width="640" alt="Image" src="https://github.com/user-attachments/assets/10d64550-9ff8-4fec-8f1c-46d20250aad2" />

The all day events are from the same week but not scheduled for today.

The only event that should show up is 7439E94B-3CA7-43BD-A63F-C260DA7E032E

**Comment by ajrosen** [comment]
I've been finding/fixing more issues with recurring events.  I don't see any errors with my own calendar now.

Assuming you ran that before midnight last Thursday, the multi-day event was listed because it only looked at the _event_'s end_date, not each individual day's end.

6A00EAC4-CAE7-465A-9CAA-18E1EB9B7343 is a recurring event?  If so, could you add the _specifier_, _frequency_, and _interval_ properties?  Those are the properties that determine an events future occurrence.  With those, I can test it to make sure that case is handled.

Thanks!

**Comment by ebartz** [comment]
Sorry, its hards for me to find everything. Can you get me the command that will search for the event `6A00EAC4-CAE7-465A-9CAA-18E1EB9B7343` and maybe also the jq filter for the specific properties you are looking for?

**Comment by ajrosen** [comment]
Sure!  This will get _everything_ icalPal uses to determine if an event should be included in the output.

`icalPal --cmd events --nrd --df %s --tf %s --iep UUID,datetime,start_date,sdate,sctime,end_date,edate,ectime,rdate,xdate,has_recurrences,specifier,frequency,interval,status --from 2025-2-4 --days 3 --match UUID=6A00EAC4`

It's restricted to three days, from 4-Feb-2025 to 6-Feb-2025, and only events with _6A00EAC4_ in the UUID.

**Comment by ebartz** [comment]
For some reason, the match filter did not work, so here you have the list without the filter:

```
• D43FBD71-0761-4BFC-8C00-738C327C0891
    1738627200
    start_date: 760233600
    sdate: 1738627200
    sctime: 2025-02-04 00:00:00 UTC
    end_date: 760406399
    edate: 1738713599
    ectime: 2025-02-04 23:59:59 UTC
    has_recurrences: 0
    status: none
• 0789A992-D1DF-4084-B30F-767B803D6313
    1738659600 at 1738656000 - 1738657800
    start_date: 760348800
    sdate: 1738659600
    sctime: 2025-02-04 09:00:00 +0100
    end_date: 760350600
    edate: 1738661400
    ectime: 2025-02-04 09:30:00 +0100
    has_recurrences: 0
    status: confirmed
• 23BD21C1-6938-480D-BDA9-1122AA34E858
    1738661400 at 1738657800 - 1738665000
    start_date: 760350600
    sdate: 1738661400
    sctime: 2025-02-04 09:30:00 +0100
    end_date: 760357800
    edate: 1738668600
    ectime: 2025-02-04 11:30:00 +0100
    has_recurrences: 0
    status: confirmed
• 2D301B36-C6EF-4F26-8437-058FB4D34DEE
    1738666800 at 1738663200 - 1738665000
    start_date: 760356000
    sdate: 1738666800
    sctime: 2025-02-04 11:00:00 +0100
    end_date: 760357800
    edate: 1738668600
    ectime: 2025-02-04 11:30:00 +0100
    has_recurrences: 0
    status: confirmed
• 43B69C10-C536-4D9D-8104-6E2B2F270AB3
    1738674000 at 1738670400 - 1738677600
    start_date: 760363200
    sdate: 1738674000
    sctime: 2025-02-04 13:00:00 +0100
    end_date: 760370400
    edate: 1738681200
    ectime: 2025-02-04 15:00:00 +0100
    has_recurrences: 0
    status: confirmed
• AFB88686-D6A9-462F-A755-08E8FB107587
    1738683000 at 1738679400 - 1738684800
    start_date: 760372200
    sdate: 1738683000
    sctime: 2025-02-04 15:30:00 +0100
    end_date: 760377600
    edate: 1738688400
    ectime: 2025-02-04 17:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 80C360AB-FF8D-46D6-A3E3-2F80A24294A9
    1738679700 at 1738679700 - 1738681200
    start_date: 759764100
    sdate: 1738679700
    sctime: 2025-02-04 14:35:00 UTC
    end_date: 759765600
    edate: 1738681200
    ectime: 2025-02-04 15:00:00 UTC
    xdate: 1739284500; 1743518100; 1739889300; 1741703700; 1745937300; 1744727700
    has_recurrences: 1
    specifier: D=0TU
    frequency: 2
    interval: 1
    count: 0
    status: confirmed
• 2226BA36-C136-4E42-AB0E-55FFE5B1B38A
    1738726200 at 1738722600 - 1738726200
    start_date: 760415400
    sdate: 1738726200
    sctime: 2025-02-05 03:30:00 +0100
    end_date: 760419000
    edate: 1738729800
    ectime: 2025-02-05 04:30:00 +0100
    has_recurrences: 0
    status: confirmed
• E14CD837-2771-4077-BD08-265C84BBF04E
    1738749600 at 1738746000 - 1738749600
    start_date: 760438800
    sdate: 1738749600
    sctime: 2025-02-05 10:00:00 +0100
    end_date: 760442400
    edate: 1738753200
    ectime: 2025-02-05 11:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 41D9EE14-0A77-4FBF-892A-45B2B6397D4D
    1738753200 at 1738749600 - 1738751400
    start_date: 760442400
    sdate: 1738753200
    sctime: 2025-02-05 11:00:00 +0100
    end_date: 760444200
    edate: 1738755000
    ectime: 2025-02-05 11:30:00 +0100
    has_recurrences: 0
    status: confirmed
• 777EEAB9-0642-41D1-AAE8-1873B0A10200
    1738755000 at 1738751400 - 1738752000
    start_date: 760444200
    sdate: 1738755000
    sctime: 2025-02-05 11:30:00 +0100
    end_date: 760444800
    edate: 1738755600
    ectime: 2025-02-05 11:40:00 +0100
    has_recurrences: 0
    status: confirmed
• BD2D6F66-EB3C-4C36-B42F-4E792F998C47
    1738756800 at 1738756800 - 1738764000
    start_date: 758631600
    sdate: 1738756800
    sctime: 2025-02-05 12:00:00 UTC
    end_date: 758638800
    edate: 1738764000
    ectime: 2025-02-05 14:00:00 UTC
    rdate: 1743638399
    xdate: 1738152000; 1736942400
    has_recurrences: 1
    specifier: D=0WE
    frequency: 2
    interval: 1
    count: 0
    status: none
• AF102ADF-97A3-41E5-9AEA-19D8DC6CE1FF
    1738760400 at 1738756800 - 1738764000
    start_date: 760449600
    sdate: 1738760400
    sctime: 2025-02-05 13:00:00 +0100
    end_date: 760456800
    edate: 1738767600
    ectime: 2025-02-05 15:00:00 +0100
    has_recurrences: 0
    status: confirmed
• F78FE4AB-0BEC-4FFD-BEA4-73B037091222
    1738771200 at 1738767600 - 1738771200
    start_date: 760460400
    sdate: 1738771200
    sctime: 2025-02-05 16:00:00 +0100
    end_date: 760464000
    edate: 1738774800
    ectime: 2025-02-05 17:00:00 +0100
    has_recurrences: 0
    status: confirmed
• C9D447D7-DB06-45AE-8F60-15562C4FA1DF
    1738774800 at 1738771200 - 1738772100
    start_date: 760464000
    sdate: 1738774800
    sctime: 2025-02-05 17:00:00 +0100
    end_date: 760464900
    edate: 1738775700
    ectime: 2025-02-05 17:15:00 +0100
    has_recurrences: 0
    status: confirmed
• 36C612A1-F17E-4B37-A8B2-D4A7C680DC0D
    1738778400 at 1738774800 - 1738777500
    start_date: 760467600
    sdate: 1738778400
    sctime: 2025-02-05 18:00:00 +0100
    end_date: 760470300
    edate: 1738781100
    ectime: 2025-02-05 18:45:00 +0100
    has_recurrences: 0
    status: confirmed
• AC5E66F6-0F90-43DE-8315-DB3CD10F7B30
    1738800000
    start_date: 760492800
    sdate: 1738800000
    sctime: 2025-02-06 01:00:00 +0100
    end_date: 760579199
    edate: 1738886399
    ectime: 2025-02-07 00:59:59 +0100
    has_recurrences: 0
    status: confirmed
• AFA1AB4D-92ED-4131-9316-4F38DF1B88D7
    1738828800 at 1738825200 - 1738839600
    start_date: 760518000
    sdate: 1738828800
    sctime: 2025-02-06 08:00:00 +0100
    end_date: 760532400
    edate: 1738843200
    ectime: 2025-02-06 12:00:00 +0100
    has_recurrences: 0
    status: none
• DF5DAF26-707F-4E8C-8934-8833CBD16386
    1738832400 at 1738828800 - 1738861200
    start_date: 760521600
    sdate: 1738832400
    sctime: 2025-02-06 09:00:00 +0100
    end_date: 760554000
    edate: 1738864800
    ectime: 2025-02-06 18:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 76E0E5FF-99D6-4F40-AE20-E7038236D8F7
    1738843200 at 1738839600 - 1738842300
    start_date: 760532400
    sdate: 1738843200
    sctime: 2025-02-06 12:00:00 +0100
    end_date: 760535100
    edate: 1738845900
    ectime: 2025-02-06 12:45:00 +0100
    has_recurrences: 0
    status: confirmed
• BE359402-B949-41F3-9817-A1E6C9E45FF5
    1738861200 at 1738857600 - 1738859400
    start_date: 760550400
    sdate: 1738861200
    sctime: 2025-02-06 17:00:00 +0100
    end_date: 760552200
    edate: 1738863000
    ectime: 2025-02-06 17:30:00 +0100
    has_recurrences: 0
    status: confirmed
• 9C9311EF-8D56-43C5-857F-7703FC400862
    1738866600 at 1738866600 - 1738870500
    start_date: 760559400
    sdate: 1738866600
    sctime: 2025-02-06 19:30:00 +0100
    end_date: 760563300
    edate: 1738870500
    ectime: 2025-02-06 20:35:00 +0100
    has_recurrences: 0
    status: confirmed
• CCAFE34C-4491-46C8-90F1-714413BD0A88
    1738921500 at 1738917900 - 1738918800
    start_date: 760610700
    sdate: 1738921500
    sctime: 2025-02-07 09:45:00 +0100
    end_date: 760611600
    edate: 1738922400
    ectime: 2025-02-07 10:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 71781F20-1563-4057-9101-689EDB291B12
    1738918800 at 1738918800 - 1738920600
    start_date: 758793600
    sdate: 1738918800
    sctime: 2025-02-07 09:00:00 UTC
    end_date: 758795400
    edate: 1738920600
    ectime: 2025-02-07 09:30:00 UTC
    has_recurrences: 1
    specifier: D=0FR
    frequency: 2
    interval: 1
    count: 0
    status: confirmed
• 090FAD4C-E49A-41F0-AC70-D8648624F621
    1738922400 at 1738918800 - 1738921500
    start_date: 760611600
    sdate: 1738922400
    sctime: 2025-02-07 10:00:00 +0100
    end_date: 760614300
    edate: 1738925100
    ectime: 2025-02-07 10:45:00 +0100
    xdate: 1738922400
    has_recurrences: 0
    status: none
• 01A1A338-E9A2-4095-B8FE-018358489E16
    1738922400 at 1738918800 - 1738921500
    start_date: 760611600
    sdate: 1738922400
    sctime: 2025-02-07 10:00:00 +0100
    end_date: 760614300
    edate: 1738925100
    ectime: 2025-02-07 10:45:00 +0100
    has_recurrences: 0
    status: confirmed
• EACA4FD0-5E3C-4886-AA83-ACB29B565083
    1738926000 at 1738922400 - 1738926000
    start_date: 760615200
    sdate: 1738926000
    sctime: 2025-02-07 11:00:00 +0100
    end_date: 760618800
    edate: 1738929600
    ectime: 2025-02-07 12:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 49D6432D-8841-405F-A2DE-F6F958B33B74
    1738929600 at 1738929600 - 1738936800
    start_date: 758804400
    sdate: 1738929600
    sctime: 2025-02-07 12:00:00 UTC
    end_date: 758811600
    edate: 1738936800
    ectime: 2025-02-07 14:00:00 UTC
    rdate: 1743811199
    xdate: 1737720000; 1737115200; 1743768000
    has_recurrences: 1
    specifier: D=0FR
    frequency: 2
    interval: 1
    count: 0
    status: none
• A2E7FF26-8D9E-4AFB-94B7-770B22BF5DFD
    1738938900 at 1738935300 - 1738937100
    start_date: 760628100
    sdate: 1738938900
    sctime: 2025-02-07 14:35:00 +0100
    end_date: 760629900
    edate: 1738940700
    ectime: 2025-02-07 15:05:00 +0100
    has_recurrences: 0
    status: confirmed
• 5B42725D-1442-48ED-BD70-33691C4388C9
    1738936800 at 1738936800 - 1738940400
    start_date: 758811600
    sdate: 1738936800
    sctime: 2025-02-07 14:00:00 UTC
    end_date: 758815200
    edate: 1738940400
    ectime: 2025-02-07 15:00:00 UTC
    rdate: 1751327999
    xdate: 1741356000; 1744984800; 1743170400; 1749218400; 1748613600; 1740146400; 1737727200; 1744380000; 1739541600; 1747404000; 1745589600; 1746194400; 1749823200; 1742565600; 1743775200
    has_recurrences: 1
    specifier: D=0FR
    frequency: 2
    interval: 1
    count: 0
    status: none
• C8A25A43-A6AB-4109-849D-A849EFE129B8
    1738940400 at 1738936800 - 1738940400
    start_date: 760629600
    sdate: 1738940400
    sctime: 2025-02-07 15:00:00 +0100
    end_date: 760633200
    edate: 1738944000
    ectime: 2025-02-07 16:00:00 +0100
    has_recurrences: 0
    status: confirmed
• 01215993-D5A5-4914-B552-733219110507
    1738944000 at 1738940400 - 1738943100
    start_date: 760633200
    sdate: 1738944000
    sctime: 2025-02-07 16:00:00 +0100
    end_date: 760635900
    edate: 1738946700
    ectime: 2025-02-07 16:45:00 +0100
    has_recurrences: 0
    status: confirmed
```
